title: Confer
description: Confer helps you build a personal schedule for conference you are attending. It helps you decide where to spend your precious time by providing social recommendations based on your interests.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
